### ISSUE TITLE
index.html being generated based on root folder and not subfolder

### ISSUE THREAD

**Issue by gabriellisboa** [PavanMudigonda/allure-html-reporter-github-pages#3]
Hello Pavan! First, thank you for making this action available.

I have a doubt about creating the index.html using the history of a subfolder rather than the repository's root folder.
I have the following structure:

```
.
├── index.html <- manually generated index to lead developers to the subfolders
├── pr
│      ├── PR_RELATED_STUFF
│      ├── ...  
└── sandbox 
        ├── index.html
        ├── 1 < - folders generated by allure-html-reporter-github-pages
        ├── 2
        ├── ...
```
Inside `sandbox/index.html`, I want the list of allure results inside the `sandbox` folder.
The content should be:
```
├── <a href=./3/index.html>RUN ID: 3- 2023-05-31 13:50:43 UTC(Latest)</a><br>
├── <a href=./2/>RUN ID: 2-   </a><br>
├── <a href=./1/>RUN ID: 1-   </a><br>
```
But instead, the generated file always has the last run and the root repository folders like this:

```
├── <a href=./855/index.html>RUN ID: 3 - 2023-05-31 13:50:43 UTC(Latest)</a><br>
├── <a href=./pr/>RUN ID: pr -   </a><br>
├── <a href=./sandbox/>RUN ID: sandbox -   </a><br>
```

I'm running the action like the following:

```
publish_e2e_tests:
    runs-on: ubuntu-20.04
    needs: [ run_e2e_tests ]
    steps:
      - name: Get Allure history
        uses: actions/checkout@v3
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Download Test Results
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: results

      - name: Allure Report
        uses: PavanMudigonda/allure-html-reporter-github-pages@v1.2
        with:
          workflow_id: ${{ github.workflow }}
          allure_results: results
          keep_reports: 20

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_PAGES_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          destination_dir: sandbox
          keep_files: true
          exclude_assets: '.github,pr,sandbox'
```

I've tried to use `subfolder` without success. Is there a way to generate the index.html based on the content of a subfolder?

I appreciate any help you can give me.
